name = "polycoudle"
main = "src/worker.js"
compatibility_date = "2025-05-01"

[assets]
directory = "./public"
binding = "ASSETS"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "vilk_weather"
database_id = "78298daa-2851-4646-9659-e47fac440a74"
